import React from 'react';
import { motion } from 'motion/react';
import { Layers, Box, Maximize, Palette } from 'lucide-react';

export default function CreativeModule() {
  return (
    <div className="h-full bg-transparent p-10 overflow-y-auto">
      <div className="flex items-start justify-between mb-16">
        <div className="space-y-1">
          <div className="text-[10px] tracking-[0.4em] uppercase font-bold text-[#00D1FF]">Creative Direction</div>
          <h2 className="text-4xl font-serif italic tracking-tighter text-[#F5F5F5]">Visual Synthesis</h2>
        </div>
        <div className="flex gap-4">
          <button className="px-6 py-2 border border-[#333] rounded-sm text-[10px] tracking-widest font-mono hover:border-[#00D1FF] hover:text-[#00D1FF] transition-colors uppercase">Export_Manifest</button>
          <button className="px-6 py-2 bg-[#F5F5F5] text-black rounded-sm text-[10px] tracking-widest font-mono font-bold hover:bg-[#F5F5F5]/90 transition-colors uppercase">Gen_Asset</button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-12">
        <ColorCard color="#FF3E00" label="SVELTE_CORE" hex="#FF3E00" />
        <ColorCard color="#00D1FF" label="CYAN_ACCENT" hex="#00D1FF" />
        <ColorCard color="#E0E0E0" label="PAPER_NEUTRAL" hex="#E0E0E0" />
        <ColorCard color="#1A1A1A" label="VOID_BLACK" hex="#1A1A1A" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 h-[400px]">
        <div className="lg:col-span-8 p-12 bg-[#050505] border border-[#1A1A1A] relative overflow-hidden group flex flex-col justify-center">
            <div className="absolute top-0 right-0 p-6">
              <Maximize className="text-white/20 w-4 h-4 hover:text-[#00D1FF] cursor-pointer transition-colors" />
            </div>
            
            <div className="text-[180px] font-serif italic opacity-[0.03] absolute left-[-20px] top-[-40px] pointer-events-none select-none">
                G
            </div>

            <div className="relative z-10 flex items-center gap-10">
              <div className="w-32 h-32 border border-white/10 rounded-full flex items-center justify-center relative">
                 <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-[#00D1FF] to-[#FF3E00] opacity-20 blur-2xl animate-pulse" />
                 <div className="w-16 h-16 rounded-full border border-[#00D1FF]/40 animate-spin-slow absolute" />
                 <div className="w-2 h-2 rounded-full bg-white shadow-[0_0_10px_white]" />
              </div>
              <div>
                <h3 className="text-2xl font-serif italic mb-2 tracking-tighter">Neo-Brutalist Void</h3>
                <p className="text-sm text-[#CCC] max-w-sm leading-relaxed opacity-60">
                    A design system built on high-contrast interfaces and mathematical spacing constants. Optimized for high-density professional workloads.
                </p>
              </div>
            </div>
        </div>

        <div className="lg:col-span-4 p-8 border border-[#1A1A1A] bg-[#050505] flex flex-col">
            <h3 className="text-[10px] font-mono text-white/40 mb-8 uppercase tracking-[0.3em]">Design Tokens</h3>
            <div className="flex-1 space-y-6">
                <TokenRow label="Border Width" value="0.5px" />
                <TokenRow label="Letter Spacing" value="0.4em" />
                <TokenRow label="Font Weight" value="200" />
                <TokenRow label="Accent Color" value="#00D1FF" />
            </div>
            <div className="mt-8 pt-8 border-t border-[#1A1A1A]">
                <p className="text-[9px] text-[#F5F5F5]/20 font-mono tracking-tighter uppercase leading-loose">
                    Generated by KONDA Personal OS. Assets are mathematically synchronized for optimal visual balance.
                </p>
            </div>
        </div>
      </div>
    </div>
  );
}

function ColorCard({ color, label, hex }: { color: string, label: string, hex: string }) {
  return (
    <div className="group cursor-pointer">
      <div 
        className="h-24 border border-[#333] transition-all duration-500 group-hover:border-[#00D1FF] flex items-end p-3 relative overflow-hidden" 
        style={{ backgroundColor: color }} 
      >
          <div className="absolute top-2 right-2 text-[8px] font-mono text-black/40 font-bold opacity-0 group-hover:opacity-100 transition-opacity">COPY</div>
      </div>
      <div className="mt-2 flex justify-between items-center">
        <span className="text-[9px] font-mono tracking-widest text-[#F5F5F5]/40 uppercase">{label}</span>
        <span className="text-[9px] font-mono text-[#F5F5F5]/20">{hex}</span>
      </div>
    </div>
  )
}

function TokenRow({ label, value }: { label: string, value: string }) {
  return (
    <div className="flex justify-between items-baseline py-1 border-b border-[#1A1A1A]">
      <span className="text-[10px] text-white/30 uppercase tracking-widest">{label}</span>
      <span className="text-xs font-mono text-[#F5F5F5]">{value}</span>
    </div>
  )
}
