import React, { useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Download } from 'lucide-react';

interface StreamingMarkdownProps {
  content: string;
  shouldAnimate: boolean;
  onComplete?: () => void;
}

export function StreamingMarkdown({ content, shouldAnimate, onComplete }: StreamingMarkdownProps) {
  const onCompleteRef = useRef(onComplete);

  useEffect(() => {
    onCompleteRef.current = onComplete;
  }, [onComplete]);

  useEffect(() => {
    if (shouldAnimate) {
      // Defer completion call slightly to ensure parent state updates happen outside of the active render cycle
      const timer = setTimeout(() => {
        onCompleteRef.current?.();
      }, 50);
      return () => clearTimeout(timer);
    }
  }, [shouldAnimate]);

  return (
    <ReactMarkdown 
      remarkPlugins={[remarkGfm]}
      components={{
        p: ({ children }) => {
          const hasImage = React.Children.toArray(children).some(
            (child: any) => {
              if (!child) return false;
              if (child.type === 'img') return true;
              if (child.props && (child.props.src || child.props.href)) return true;
              return false;
            }
          );
          if (hasImage) {
            return <div className="mb-4 space-y-2">{children}</div>;
          }
          return <p className="mb-4 leading-relaxed text-white/80">{children}</p>;
        },
        img: ({ src, alt }) => {
          return (
            <div className="my-4 flex flex-col gap-2 max-w-lg">
              <div className="relative group rounded-xl overflow-hidden border border-white/10 bg-black/40">
                <img 
                  src={src} 
                  alt={alt} 
                  referrerPolicy="no-referrer"
                  className="w-full h-auto object-cover max-h-[500px] transition-transform duration-300 group-hover:scale-[1.01]" 
                />
                
                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4">
                  <a 
                    href={src} 
                    download={`${alt || 'konda-synth'}.png`}
                    className="p-3 bg-white/10 hover:bg-[#FF3E00]/20 hover:text-[#FF3E00] border border-white/10 rounded-full transition-all flex items-center gap-2 text-xs font-mono uppercase text-white shadow-xl cursor-pointer"
                  >
                    <Download className="w-4 h-4" />
                    Download
                  </a>
                </div>
              </div>
              <div className="flex justify-between items-center px-1 text-[10px] font-mono text-white/30">
                <span>{alt || 'FLUX SYNTHESIS'}</span>
                <span className="text-[#FF3E00]/60">GENERATED BY KONDA AI</span>
              </div>
            </div>
          );
        }
      }}
    >
      {content}
    </ReactMarkdown>
  );
}
